ALTER TABLE students
ADD COLUMN date_of_birth DATE NOT NULL;

ALTER TABLE students
ADD COLUMN street VARCHAR(255);
ALTER TABLE students
ADD COLUMN city VARCHAR(100);
ALTER TABLE students
ADD COLUMN province VARCHAR(100);
ALTER TABLE students
ADD COLUMN country VARCHAR(100);
ALTER TABLE students
ADD COLUMN postal_code VARCHAR(50);
